camera:
  aspect_ratio: 1.7778
  image_width: 400
  samples_per_pixel: 100
  max_depth: 50
  vfov: 20.0
  lookfrom: [3.0, 2.0, -9.0]
  lookat: [0.0, 0.0, 0.0]
  vup: [0.0, 1.0, 0.0]
  brightness: 1.0

materials:
  [
    ground: { type: Lambertian, colour: [0.5, 0.5, 0.5] },
    cylin: { type: Lambertian, colour: [0.0, 1.0, 0.5] },
    centre: { type: Metal, colour: [0.7, 0.3, 0.3] },
  ]

objects:
  [
    { type: Plane, mat: ground },
    { type: Sphere, centre: [2.0, 0.0, -1.0], radius: 0.5, mat: centre },
    { type: Cylinder, mat: cylin },
  ]

filename: image
